steps:

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['config', 'set', 'project', 'thebridgeschool-cloud']

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/users-app-client:$COMMIT_SHA', '-f', 'client/Dockerfile', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/users-app-client:$COMMIT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args: [
    "-c",
    "gcloud run deploy react-nodejs-cloudbuilds-client 
    --image=gcr.io/$PROJECT_ID/users-app-client:$COMMIT_SHA 
    --region=europe-west1 
    --platform=managed 
    --allow-unauthenticated 
    --port=5173 
    --update-env-vars DB_URL_ATLAS=$$DB_URL_ATLAS"
  ]

  secretEnv: [
    'DB_URL_ATLAS'
  ]
images:
- 'gcr.io/$PROJECT_ID/users-app-client:$COMMIT_SHA'

availableSecrets:
  secretManager:
    - versionName: projects/623401579225/secrets/DB_URL_ATLAS/versions/latest
      env: 'DB_URL_ATLAS'